apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: dev-stagelog
  namespace: argocd

spec:
  description: Dev environment project

  sourceRepos:
    - https://github.com/Goorm-Team-Project/stagelog-gitops.git

  destinations:
    - namespace: dev-*
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

    