installCRDs: true

serviceAccount:
  create: true
  name: "external-secrets"
  annotations:
    # 테라폼으로 만든 IAM Role의 주소(ARN)\
    eks.amazonaws.com/role-arn: "arn:aws:iam::430118823715:role/stagelog-eso-role"