deployment:
  enabled: false

service:
  enabled: false
 
ingress:
  enabled: false

secret:
  enabled: true

  name: dev-auth-secret
  targetName: dev-auth-secret

  storeName: aws-parameterstore
  storeKind: ClusterSecretStore

  refreshInterval: 1h

  path: /stagelog/dev/auth/

serviceAccount:
  enabled: false
  