deployment:
  enabled: false

service:
  enabled: false
 
ingress:
  enabled: false

secret:
  enabled: true

  name: dev-posts-secret
  targetName: dev-posts-secret

  storeName: aws-parameterstore
  storeKind: ClusterSecretStore

  refreshInterval: 1h

  path: /stagelog/dev/posts/

serviceAccount:
  enabled: false
  