{{- if .Values.alertmanagerConfigExternalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.alertmanagerConfigExternalSecret.name }}
  namespace: {{ .Values.alertmanagerConfigExternalSecret.namespace }}
spec:
  refreshInterval: {{ .Values.alertmanagerConfigExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.alertmanagerConfigExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.alertmanagerConfigExternalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.alertmanagerConfigExternalSecret.target.name }}
    creationPolicy: {{ .Values.alertmanagerConfigExternalSecret.target.creationPolicy }}
  data:
{{ toYaml .Values.alertmanagerConfigExternalSecret.data | indent 4 }}
{{- end }}

