{{- if .Values.discordWebhookExternalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.discordWebhookExternalSecret.name }}
  namespace: {{ .Values.discordWebhookExternalSecret.namespace }}
spec:
  refreshInterval: {{ .Values.discordWebhookExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.discordWebhookExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.discordWebhookExternalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.discordWebhookExternalSecret.target.name }}
    creationPolicy: {{ .Values.discordWebhookExternalSecret.target.creationPolicy }}
  data:
{{ toYaml .Values.discordWebhookExternalSecret.data | indent 4 }}
{{- end }}
