apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: dev-stagelog
  source:
    repoURL: 'https://github.com/Goorm-Team-Project/stagelog-gitops.git'
    targetRevision: main
    path: charts/loki
    helm:
      valueFiles:
        - values/dev/loki.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # namespace 단일화
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true