apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: {{ .Values.nodeRole }}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: {{ .Values.clusterName }}

  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: {{ .Values.clusterName }}

  tags:
    Name: "stagelog-karpenter-node"
    intent: "apps"
    managed-by: "karpenter"