apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter
  namespace: karpenter
  annotations:
    # 여기에 테라폼 apply 후 나온 'aws_iam_role.karpenter_controller_role.arn'을 넣으세요.
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}