{{- if (.Values.deployment.enabled | default false) }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{  include "backend.fullname" . }}
  labels:
    app: {{ .Values.name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.name }}

  template:
    metadata:
      labels: 
        app.kubernetes.io/instance: {{ .Values.name }}
        app: {{ .Values.name }}

    spec:
      {{- if (.Values.deployment.enabled | default false) }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end}}

      containers:
        - name: {{ .Values.name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}

          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          
      
{{- end }}