{{- if (.Values.deployment.enabled | default false) }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{  include "backend.fullname" . }}
  labels:
    app: {{ .Values.name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.name }}

  template:
    metadata:
      labels: 
        app.kubernetes.io/instance: {{ .Values.name }}
        app: {{ .Values.name }}

    spec:
      containers:
        - name: {{ .Values.name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      #     volumeMounts:
      #           {{- with .Values.extraVolumeMounts }}
      #           {{- toYaml . | nindent 6 }}
      #           {{- end }}

      # volumes:
      #   {{- with .Values.extraVolumes }}
      #   {{- toYaml . | nindent 2 }}
      #   {{- end }}
{{- end }}