{{- if (.Values.secret.enabled | default false) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: {{ .Values.secret.name }}

spec:
  refreshInterval: {{ .Values.secret.refreshInterval | default "1h" }}

  secretStoreRef:
    name: {{ .Values.secret.storeName }}
    kind: {{ .Values.secret.storeKind | default "ClusterSecretStore" }}

  target:
    name: {{ .Values.secret.targetName }}
    creationPolicy: Owner

  data:
    - secretKey: DB_NAME_POSTS
      remoteRef:
        key: {{ .Values.secret.path }}DB_NAME_POSTS

{{- end }}