{{- if (.Values.ingress.enabled | default false) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - http:
        paths:
{{- range .Values.ingress.rules }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
{{- end }}
{{- end }}