apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd

data:
# ArgoCD UI 접속 주소
  url: https://localhost:8080

# ArgoCD가 리소스를 추적하는 방식
# annotation | label | annotation+label
  application.resourceTrackingMethod: annotation+label


