apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd

data:
  application.instanceLabelKey: argocd.argoproj.io/instance # 기존키 가져오기
  timeout.reconciliation: 180s
  application.resourceTrackingMethod: annotation+label # ArgoCD가 리소스를 추적하는 방식
# # ArgoCD UI 접속 주소
#   #url: https://localhost:8080





