apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/Goorm-Team-Project/stagelog-gitops.git
    targetRevision: develop
    path: apps/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  ignoreDifferences:
  # Deployment용
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  
  # Rollout용 (Argo Rollout API 그룹)
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true