apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dev-applications.yaml
  - dev-projects.yaml
  - platforms.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    path: argocd-cm-patch.yaml