name: dev-auth

deployment:
  enabled: true

replicaCount: 1

image:
  repository: 430118823715.dkr.ecr.ap-northeast-2.amazonaws.com/stagelog-backend
  tag: latest
  pullPolicy: Always

extraVolumeMounts:
  - name: env-file
    mountPath: /app/.env
    subPath: .env

extraVolumes:
  - name: env-file
    secret:
      secretName: dev-secret

service:
  enabled: true
  name: auth-svc
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  name: stagelog-public-api
  className: alb

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/group.name: stagelog-public-api
  
  
  rules:
    - path: /api/users
      serviceName: auth-svc
      servicePort: 8000

    - path: /api/users/
      serviceName: auth-svc
      servicePort: 8000
    
    - path: /prod/api/users/
      serviceName: auth-svc
      servicePort: 8000
    
    - path: /prod/api/users
      serviceName: auth-svc
      servicePort: 8000

    - path: /api/events
      serviceName: events-svc
      servicePort: 8000

    - path: /api/events/
      serviceName: events-svc
      servicePort: 8000
    
    - path: /prod/api/events
      serviceName: events-svc
      servicePort: 8000

    - path: /prod/api/events/
      serviceName: events-svc
      servicePort: 8000

    - path: /api/bookmarks
      serviceName: auth-svc
      servicePort: 8000

    - path: /api/bookmarks/
      serviceName: auth-svc
      servicePort: 8000
    
    - path: /prod/api/bookmarks
      serviceName: auth-svc
      servicePort: 8000

    - path: /prod/api/bookmarks/
      serviceName: auth-svc
      servicePort: 8000
    
    - path: /api/
      serviceName: core-svc
      servicePort: 8000

    - path: /prod/api/
      serviceName: core-svc
      servicePort: 8000



resources: {}