name: dev-auth

deployment:
  enabled: true

replicaCount: 1

image:
  repository: 430118823715.dkr.ecr.ap-northeast-2.amazonaws.com/stagelog-auth
  tag: latest
  pullPolicy: Always

service:
  enabled: true
  name: auth-svc
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

secret:
  enabled: false

serviceAccount:
  enabled: false

envFromSecret: dev-auth-secret

env:
  - name: DJANGO_SETTINGS_MODULE
    value: config.settings
  
resources: {}