name: dev-core

deployment:
  enabled: true

replicaCount: 1

image:
  repository: 430118823715.dkr.ecr.ap-northeast-2.amazonaws.com/stagelog-backend
  tag: latest
  pullPolicy: Always

extraVolumeMounts:
  - name: env-file
    mountPath: /app/.env
    subPath: .env

extraVolumes:
  - name: env-file
    secret:
      secretName: dev-secret

service:
  enabled: true
  name: core-svc
  type: ClusterIP
  port: 8000

ingress:
  enabled: false