name: dev-monolith

deployment:
  enabled: true

replicaCount: 1

image:
  repository: 430118823715.dkr.ecr.ap-northeast-2.amazonaws.com/stagelog-backend
  tag: latest
  pullPolicy: Always

extraVolumeMounts:
  - name: env-file
    mountPath: /app/.env
    subPath: .env

extraVolumes:
  - name: env-file
    secret:
      secretName: dev-secret
# service:
#   type: ClusterIP
#   port: 8000

ingress:
  enabled: true
  name: stagelog-public-api
  className: alb

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:430118823715:certificate/0939ee3c-791b-464a-9d1b-0fa8ab84678e
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/group.name: stagelog-public-api

    rules:
    - host: api.pearlinvest.click
      http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 8000

          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: events-svc
                port:
                  number: 8000

          - path: /api/bookmarks
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 8000

          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: core-svc
                port:
                  number: 8000



resources: {}