rollout:
  enabled: false

name: dev-outboxworker

deployment:
  enabled: true

replicaCount: 1

image:
  repository: 430118823715.dkr.ecr.ap-northeast-2.amazonaws.com/stagelog-outbox-worker
  tag: 35912cae402b
  pullPolicy: Always

service:
  enabled: false

ingress:
  enabled: false

secret:
  enabled: false
  create: false

serviceAccount:
  enabled: true
  create: true
  name: stagelog-outbox-worker-sa
  roleArn: arn:aws:iam::430118823715:role/stagelog-outbox-worker-workload-role

envFromSecret: dev-outboxworker-secret

env:
  - name: DJANGO_SETTINGS_MODULE
    value: config.settings

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi

readinessProbe:
  enabled: false
  
livenessProbe:
  enabled: true
  type: exec
  exec:
    command:
      - sh
      - -c
      - pgrep -f worker
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
 