rollout:
  enabled: false

deployment: 
  enabled: false

service: 
  enabled: false 

ingress: 
  enabled: false 

hpa:
  enabled: false

secret: 
  enabled: true 
  name: dev-outboxworker-secret 
  targetName: dev-outboxworker-secret 
  storeName: aws-parameterstore 
  storeKind: ClusterSecretStore 
  refreshInterval: 1h 

  mappings:
  - secretKey: SECRET_KEY
    remotePath: /stagelog/dev/shared/
    remoteKey: SECRET_KEY

  - secretKey: DEBUG
    remotePath: /stagelog/dev/shared/
    remoteKey: DEBUG

  - secretKey: DB_MODE
    remotePath: /stagelog/dev/shared/
    remoteKey: DB_MODE

  - secretKey: DB_HOST
    remotePath: /stagelog/dev/shared/
    remoteKey: DB_HOST

  - secretKey: DB_NAME_POSTS
    remotePath: /stagelog/dev/posts/
    remoteKey: DB_NAME_POSTS

  - secretKey: DB_USER_POSTS
    remotePath: /stagelog/dev/posts/
    remoteKey: DB_USER_POSTS

  - secretKey: DB_PASSWORD_POSTS
    remotePath: /stagelog/dev/posts/
    remoteKey: DB_PASSWORD_POSTS

  - secretKey: DB_NAME_AUTH
    remotePath: /stagelog/dev/auth/
    remoteKey: DB_NAME_AUTH

  - secretKey: DB_USER_AUTH
    remotePath: /stagelog/dev/auth/
    remoteKey: DB_USER_AUTH

  - secretKey: DB_PASSWORD_AUTH
    remotePath: /stagelog/dev/auth/
    remoteKey: DB_PASSWORD_AUTH

  - secretKey: DB_NAME_EVENTS
    remotePath: /stagelog/dev/events/
    remoteKey: DB_NAME_EVENTS

  - secretKey: DB_USER_EVENTS
    remotePath: /stagelog/dev/events/
    remoteKey: DB_USER_EVENTS

  - secretKey: DB_PASSWORD_EVENTS
    remotePath: /stagelog/dev/events/
    remoteKey: DB_PASSWORD_EVENTS

  - secretKey: DB_USE_SSL
    remotePath: /stagelog/dev/shared/
    remoteKey: DB_USE_SSL

  - secretKey: DB_SSL_CA
    remotePath: /stagelog/dev/shared/
    remoteKey: DB_SSL_CA

  - secretKey: AWS_REGION
    remotePath: /stagelog/dev/shared/
    remoteKey: AWS_REGION

  - secretKey: NOTIFICATION_EVENT_BUS_NAME
    remotePath: /stagelog/dev/shared/
    remoteKey: NOTIFICATION_EVENT_BUS_NAME

  - secretKey: OUTBOX_DATABASES
    remotePath: /stagelog/dev/outbox-worker/
    remoteKey: OUTBOX_DATABASES

  - secretKey: OUTBOX_PUBLISH_BATCH_SIZE
    remotePath: /stagelog/dev/outbox-worker/
    remoteKey: OUTBOX_PUBLISH_BATCH_SIZE

  - secretKey: OUTBOX_MAX_RETRIES
    remotePath: /stagelog/dev/outbox-worker/
    remoteKey: OUTBOX_MAX_RETRIES

  - secretKey: OUTBOX_RETRY_BASE_DELAY_SECONDS
    remotePath: /stagelog/dev/outbox-worker/
    remoteKey: OUTBOX_RETRY_BASE_DELAY_SECONDS

  - secretKey: OUTBOX_PUBLISH_INTERVAL_SECONDS
    remotePath: /stagelog/dev/outbox-worker/
    remoteKey: OUTBOX_PUBLISH_INTERVAL_SECONDS
    
serviceAccount: 
  enabled: false
  create: false

readinessProbe:
  enabled: false

livenessProbe:
  enabled: false