name: dev-posts

deployment:
  enabled: true

replicaCount: 1

image:
  repository: 430118823715.dkr.ecr.ap-northeast-2.amazonaws.com/stagelog-posts
  tag: 817be585d5c5
  pullPolicy: Always

service:
  enabled: true
  name: posts-svc
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

secret:
  enabled: false

serviceAccount:
  enabled: true
  create: true
  name: stagelog-posts-sa
  roleArn: arn:aws:iam::430118823715:role/stagelog-posts-workload-role

envFromSecret: dev-posts-secret

env:
  - name: DJANGO_SETTINGS_MODULE
    value: config.settings

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 512Mi