deployment:
  enabled: false

service:
  enabled: false
 
ingress:
  enabled: false

secret:
  enabled: false

serviceAccount:
  enabled: true
  create: true
  name: stagelog-backend-sa
  roleArn: arn:aws:iam::430118823715:role/stagelog-backend-workload-role
  