kube-prometheus-stack:
  _onDemandNodeSelector: &onDemandNodeSelector
    eks.amazonaws.com/capacityType: ON_DEMAND

  crds:
    enabled: false
    upgradeJob:
      enabled: false

  # kube-system 네임스페이스에 Service/ServiceMonitor 등을 생성하는 컴포넌트 비활성화
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  coreDns:
    enabled: false

  grafana:
    nodeSelector: *onDemandNodeSelector
    adminPassword: "admin"
    dashboards:
      default:
        node-exporter:
          gnetId: 1860
          revision: 31
          datasource: "Prometheus"
        k8s-compute-resources:
          gnetId: 315
          revision: 3
          datasource: "Prometheus"
    persistence:
      enabled: false
    # Loki
    additionalDatasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        isDefault: false
        jsonData:
          maxLines: 1000

  prometheus:
    prometheusSpec:
      nodeSelector: *onDemandNodeSelector
      scrapeInterval: "30s"
      scrapeTimeout: "10s"
      retention: "15d"
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector:
        matchLabels:
          release: "prometheus-stack"

  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'job']
        receiver: 'discord'
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 12h
      receivers:
      - name: 'null'
        # chart 기본값과의 호환용 (undefined receiver "null" 방지)
      - name: 'discord'
        discord_configs:
        - webhook_url: 'https://discord.com/api/webhooks/1484360294120820766/Cr-uxvkwGphDwyMS0GnIMGE8cgIaAAtTks159QVvj9D8b9dFbUzGTYN-MIEINpRCpz_I'
          send_resolved: true
    alertmanagerSpec:
      nodeSelector: *onDemandNodeSelector

  prometheusOperator:
    nodeSelector: *onDemandNodeSelector
    admissionWebhooks:
      enabled: true

  prometheus-node-exporter:
    prometheus:
      monitor:
        enabled: true

  kube-state-metrics:
    nodeSelector: *onDemandNodeSelector