apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev-monolith
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: dev-stagelog
  
  source:
    repoURL: https://github.com/Goorm-Team-Project/stagelog-gitops.git
    targetRevision: develop
    path: charts/backend

    helm:
      valueFiles:
        - values/dev/monolith.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-monolith

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true