apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-env
  namespace: backend
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore

  target:
    name: backend-env
    creationPolicy: Owner

  data:
    - secretKey: .env
      remoteRef:
        key: /stagelog/backend/.env