apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev-notifications-consumer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: dev-stagelog
  
  source:
    repoURL: https://github.com/Goorm-Team-Project/stagelog-gitops.git
    targetRevision: develop
    path: charts/backend

    helm:
      valueFiles:
        - values/dev/notifications-consumer.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true