apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-secret
  namespace: dev-backend
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore

  target:
    name: dev-secret
    creationPolicy: Owner

  data:
    - secretKey: .env
      remoteRef:
        key: /stagelog/backend/.env