replicaCount: 1

image:
  repository: nginx
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: alb

  host: 
  path: /

  annotations: {}
    

  tls: false
  tlsSecret: ""
resources: {}

configs:
  cm:
    # ArgoCD가 리소스를 추적하는 방식을 annotation과 label 모두 사용하도록 설정
    application.resourceTrackingMethod: "annotation+label"