apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    #argocd.argoproj.io/sync-wave: "-1" # external-secrets(-2) 다음에 배포
spec:
  project: dev-stagelog
  source:
    repoURL: 'https://github.com/Goorm-Team-Project/stagelog-gitops.git'
    targetRevision: develop
    path: charts/prometheus
    helm:
      valueFiles:
        - values/dev/prometheus.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true