apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   

spec:
  project: dev-stagelog

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.35.0

    helm:
      parameters:
        - name: installCRDs
          value: "true"

        - name: controller.resources.requests.cpu
          value: "100m"
        - name: controller.resources.requests.memory
          value: "128Mi"

        - name: controller.resources.limits.cpu
          value: "500m"
        - name: controller.resources.limits.memory
          value: "512Mi"

        - name: dashboard.enabled
          value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true